### PR TITLE
check_asm: vvc_deblock, align code to hevc_deblock.c

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
@stone-d-chen , why we remove this line will fail the checkasm https://github.com/stone-d-chen/ffvvc/pull/7/files#diff-f59f253bbc1b4759e02de771f99edf3638c3ca7bd8d6fe58ca4a7a7a3bc1483dR140
hevc_deblock has no such line

**Comment by stone-d-chen** [comment]
> @stone-d-chen , why we remove this line will fail the checkasm https://github.com/stone-d-chen/ffvvc/pull/7/files#diff-f59f253bbc1b4759e02de771f99edf3638c3ca7bd8d6fe58ca4a7a7a3bc1483dR140 hevc_deblock has no such line

Hi @nuomi2021,

The two buffers will contain un-initialized data which (usually) will mismatch and fail.

In luma, it's first memset to 0's, luma randomized, then memcpy'd to the second array. I decided to just randomize the two instead and then overwrite with the strong.

https://github.com/ffvvc/FFmpeg/blob/03175b587cdc445d6d0de87ada0af0e6692e3dea/tests/checkasm/hevc_deblock.c#L232-L240

In chroma it's randomized
https://github.com/ffvvc/FFmpeg/blob/03175b587cdc445d6d0de87ada0af0e6692e3dea/tests/checkasm/hevc_deblock.c#L66

**Comment by nuomi2021** [comment]
Hi @stone-d-chen 
Thank you for the explanation. 
The memset is needed since the code does not want it to randomly decide the mode.
The randomize_luma_buffers(we have a similar code in vvc_deblock.c) function will randomize the buffer, so once we call it, we do not need to call randomize_buffers.

**Comment by stone-d-chen** [comment]
Ah right, I thought for some reason Strong generation didn't overwrite P3-Q3, ... I remember having a similar bug but I think that was maybe before I fixed the buffer size / stride.

**Comment by nuomi2021** [comment]
thank you for the merge. 
the asm code is hard to debug. This why we need to align our code to hevc strictly and review it carefully

**Comment by nuomi2021** [comment]
@stone-d-chen , wired, https://github.com/stone-d-chen/ffvvc/commits/deblocking_filter/ has no my commit. 
did you force pushed the branch?
How about we use the deblocking_filter branch (or other)as our development branch? 
Never force-push it. Just send pr to it and carefully review every pr?

thank you

**Comment by stone-d-chen** [comment]
Yeah that was my mistake, first time merging. I was trying to clean up my history first, I've cherry picked your commits.

**Comment by nuomi2021** [comment]
let us use https://github.com/ffvvc/FFmpeg/tree/deblock_asm as a development branch.
We can send pr to this branch.

**Pull request merged**
